display:
  mach: 3
  unit:
    name: "mph"
    factor: 2.23694
quarkus:
  datasource:
    db-kind: h2
    username: jcat
    password: 123
    jdbc:
      url: jdbc:h2:mem:jcatServer
  hibernate-orm:
    database:
      generation: update
    packages: org.acm.demo.model